### ISSUE TITLE
Windows compatibility of stardox

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#10]
Stardox currently supports linux platforms only and is not tested for windows platform. Looking forward to make it compatible for windows users as well.

**Comment by Chandler-Song** [comment]
I can only gathrer around 30 stargazer's info. Is it because I reach the limit?

**Comment by 0xPrateek** [comment]
hey! @Chandler-Song  thanks for commenting about the issue. It's fixed now :) you can clone and you use it again.

**Comment by Chandler-Song** [comment]
Thanks. I will try it again.

**Comment by 0xPrateek** [comment]
We officially do not support windows now.
