### ISSUE TITLE
Adding fast mode.

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#12]
Stardox takes a lot of time to come up with the results. This issue is made for resolving the speed problem.
I have listed things we can do for speeding it up (Or for the fast mode.) :
* Removing the email fetching (getting an email is very time taking task.)
* no verbose (Following Issue #11)
* using multithreading (Following issue #5 )

**Comment by CaineArdayfio** [comment]
Hello, I would like to work on this issue. It seems that @0xPrateek  has already implemented a no versos mode. I would like to work on removing the email fetching in fast mode?

**Comment by 0xPrateek** [comment]
Stardox is now 5 times faster with commit a995ff7
