### ISSUE TITLE
Adding an --email only flag to stardox

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#19]
An `--email only` flag is required as it's requested by many users of stardox.
It will give us only emails of the stargazers.

**Comment by DreadKnight** [comment]
I'm definitely looking for something like this. Quite a few projects like that out there on Github, but many have dust on them...

**Comment by 0xPrateek** [comment]
Your feedback about the issue tells it importance. Will push this commit very soon.

**Comment by DreadKnight** [comment]
The email addresses should be listed one after another, separated by commas btw, in order to be easily usable.

**Comment by 0xPrateek** [comment]
Hmm... I think that will not look good on the screen. Although for this what i have thought is that when a user gives a flag of `email` and  `save` then it will store all the fetched emails in a .csv 
What you say ?

**Comment by DreadKnight** [comment]
@0xPrateek Yeah, did a bit more research since my last reply and it seems that csv is indeed the best way to go for this kind of stuff! Was about to reply that anyway :-) Hopefully you'll manage this soon btw!

**Comment by akshgpt7** [comment]
Is this issue open? I'd like to work on it!

**Comment by akshgpt7** [comment]
Please review #39 . Can I start working on this issue now?

**Comment by 0xPrateek** [comment]
@akshgpt7 Yes you can start working on this issue.
