### ISSUE TITLE
Saving information doxed into text

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#20]
With this feature, users will be able to save the doxed stargazer's information into a text file.

**Comment by DreadKnight** [comment]
I agree, this is a total must!

**Comment by akshgpt7** [comment]
Hey! I'd like to work on this issue.

**Comment by 0xPrateek** [comment]
@akshgpt7 I am assigning you this issue. Make sure to update your progress.

**Comment by akshgpt7** [comment]
I think before adding any new arguments, we need to work on issue #26 . Otherwise, more ```if-else``` statements will be added. 
I'm looking for a solution to issue #26 currently.

**Comment by akshgpt7** [comment]
I've started working on this issue. For adding new arguments, I'm making callable classes and adding them in ```action``` of the argument. This will prevent using ```if-else``` for every new argument, and make adding new arguments easier.
Can be a solution to #26.

**Comment by 0xPrateek** [comment]
I am very soon pushing a new `command line argument code`. Kindly wait for it.

**Comment by akshgpt7** [comment]
Waiting for it, because only then can I start working on my assigned issues! :)

**Comment by 0xPrateek** [comment]
@akshgpt7 I am on it. I will push a PR very soon :+1:

**Comment by 0xPrateek** [comment]
@akshgpt7  Issue #26 is fixed you can start working on this issue. and yes make sure that you store information in a csv file instead of a normal text file.

**Comment by akshgpt7** [comment]
@0xPrateek Do I make the user enter the path of the csv file in which it is to be saved or do I create a new file, if new file is created, where to create it?

**Comment by 0xPrateek** [comment]
@ ask it from the user as a command line argument and by default set it to Desktop
