### ISSUE TITLE
Error importing requests module

### ISSUE THREAD

**Issue by DreadKnight** [0xPrateek/Stardox#22]
This fails to work on my linux machine for some reason...

>dread@FreezingMoon:~$ git clone https://github.com/0xprateek/stardox
Cloning into 'stardox'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 211 (delta 15), reused 4 (delta 0), pack-reused 183
Receiving objects: 100% (211/211), 79.87 KiB | 614.00 KiB/s, done.
Resolving deltas: 100% (110/110), done.
dread@FreezingMoon:~$ cd stardox/
dread@FreezingMoon:~/stardox$ pip install -r requirements.txt
Collecting requests (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting beautifulsoup4 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f9/d9/183705a87492249b212d88eef740995f55076195bcf45ed59306c146e42d/beautifulsoup4-4.8.1-py2-none-any.whl
Collecting lxml (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/e4/f4/65d145cd6917131826050b0479be35aaccba2847b7f80fc4afc6bec6616b/lxml-4.4.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting soupsieve>=1.2 (from beautifulsoup4->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/81/94/03c0f04471fc245d08d0a99f7946ac228ca98da4fa75796c507f61e688c2/soupsieve-1.9.5-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version < "3" (from soupsieve>=1.2->beautifulsoup4->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/da/d1/080d2bb13773803648281a49e3918f65b31b7beebf009887a529357fd44a/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
Installing collected packages: urllib3, certifi, chardet, idna, requests, backports.functools-lru-cache, soupsieve, beautifulsoup4, lxml
Successfully installed backports.functools-lru-cache-1.6.1 beautifulsoup4-4.8.1 certifi-2019.9.11 chardet-3.0.4 idna-2.8 lxml-4.4.1 requests-2.22.0 soupsieve-1.9.5 urllib3-1.25.7
dread@FreezingMoon:~/stardox$ cd src/
dread@FreezingMoon:~/stardox/src$ python3 stardox.py 

           ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
          sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
         sssssss            ssssssssss      ss     ss       sss     ss      sss    ss       ss      ss   sss    sss
        sssssss               ssss        sss     sss      sss      ss     sss      ss     ss      ss     ss   ss
       ssssssssssssss        ssss        sss     sss      sss      ss     sss       ss    ss      ss      ss  ss
       ssssssssssssss       ssss        sssssssssss      sssssssssss     sss       ss    ss      ss       ssss
                ssss       ssss        sssssssssss      sssssss         sss       ss    ss      ss       ssss
               ssss       ssss        sss     sss      sss  sss        sss       ss    ss      ss       ss  ss
    ssssssssssssss       ssss        sss     sss      sss   sss       sss     ss     ssssssssss        ss   ss
  sssssssssssssss       ssss        sss     sss      sss     sss     sssssssss      ssssssssss       sss    sss        Made By : Pr0t0n
    
[-] Error importing requests module.
dread@FreezingMoon:~/stardox/src$

**Comment by 0xPrateek** [comment]
Check this issue #18 .

**Comment by DreadKnight** [comment]
@0xPrateek Thanks! I've finally managed, but that's quite tricky overall :-/
