### ISSUE TITLE
getting numbers wrong

### ISSUE THREAD

**Issue by DreadKnight** [0xPrateek/Stardox#23]
Using this for the first time and it seems to be a bit bad with the numbers when it's used on big repositories. For example the stargazers for this repo are actually 1000x bigger

>Enter the repository address :: https://github.com/freeCodeCamp/freeCodeCamp

[+] Got the repository data 
[+] Repository Title : freeCodeCamp
[+] Total watchers : 83
[+] Total stargazers : 306
[+] Total Forks : 231
[~] Fetching stargazers list
[~] Doxing started ...

**Comment by 0xPrateek** [comment]
Actually at the time of testing i haven't checked it for the case when stargazers count is more than 1k although when you will check the algorithm you will find that we are finding the usernames of all the stargazers not on the basis of the stargazers count but upto when the 'next' is having `URL` with it but at the time of doxing and displaying we are using count obtained from scraped stargazers count.

Thanks for pointing out this big issue. Will fix it soon.

**Comment by 0xPrateek** [comment]
Hey @DreadKnight..!
This issue is fixed.
Happy Doxing.! :)

**Comment by DreadKnight** [comment]
@0xPrateek Good to hear! Will check it out soon! :3
