### ISSUE TITLE
bypassing Github limitations

### ISSUE THREAD

**Issue by DreadKnight** [0xPrateek/Stardox#24]
I might be wrong on this one, but if this app doesn't use Github's security tokens, fetching member info from various repositories is severely limited to just a few entries no matter what.

`Top right avatar / Settings / Developer settings / Personal access tokens / Generate new token`

I think this raises the number from 60 entries to something like 1500 per hour. I've actually bumped into some similar app that was also working around the limitations by waiting, which is also handy!

**Comment by 0xPrateek** [comment]
What i know is that api rate limit of authenticated request is 1500/h and 60/h for non-authenticated.
Whereas on checking terms and conditions and rules for scrapping i didn't found any such limits to scrappers.

**Comment by DreadKnight** [comment]
Yeah, those sound right, encountered them before in my research, as other projects were using the API. Hopefully there are no ToS related issues indeed.
I didn't got the proper amount of results when scaping freeCodeCamp though xD

**Comment by 0xPrateek** [comment]
Freecodecamp repo has huge numbers.
And yes stardox was not tested for such big numbers.although Yesterday i tested stardox for around 200 stars and it worked perfectly.
I know it should would perfectly no matter what the number are. Can you tell what was the problem ? Upto how much you were able to scrape? Do you have any logs of error if possible?

**Comment by DreadKnight** [comment]
@0xPrateek Not sure about a number, the saved log has about 2800 lines though. There wasn't any error.
[the log 2.txt](https://github.com/0xPrateek/Stardox/files/3844685/the.log.2.txt)

**Comment by 0xPrateek** [comment]
Remember you pointed out error of wrong numbers of stargazers.
The log says that it scrapped data of about 306 users.
And as i told you earlier that since code was not tested for the case where data is more than 1000 and thus this code is neglecting x1000.
Will be fixing very soon.

**Comment by DreadKnight** [comment]
Great to hear then. Yeah, was thinking that might be the issue, looking forward to the fix and also to #19

**Comment by 0xPrateek** [comment]
I'll push these updates very soon. :+1:

**Comment by DreadKnight** [comment]
Stardox fetched more email addresses so far, but still far away from the truth, I suspend because of GH API limitations, but no error gets displayed. You should test with a big repo, like I do with freeCodeCamp

**Comment by 0xPrateek** [comment]
@DreadKnight Okay..! will test it once.
