### ISSUE TITLE
Re-writing command line arguments code.

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#26]
The current approach of command-line arguments in our code is not feasible for adding a new argument.
writing a new easy to implement command-line argument code is required to make everything simple out there.
`Make sure to update your changes and usage method in readme.md`

**Comment by raajtilaksarma** [comment]
May i know why a new argument cannot be used in the current structure? I saw `argparse` being used to parse command line arguments. Can you give a more detailed explanation of this issue?

**Comment by 0xPrateek** [comment]
Actually issue with the current implementation is whenever you need to add a new argument to your script you will need to write a new `If `- `else` block for checking if that argument is present or not.
I need a new command-line argument with optional and positional argument easily separable
.
