### ISSUE TITLE
Use PEP-8 code formatting

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#27]
Use PEP-8 standard for formatting code.
you can read about it [here](https://www.python.org/dev/peps/pep-0008/).
- For this, run the whole code through a pep-8 formatter and update new codes here.

**Comment by akshgpt7** [comment]
Is anyone else working on this issue? Of not, then can I take it up?

**Comment by 0xPrateek** [comment]
Yes..! It is open.
I am assigning you this issue. make sure you update your progress by commenting.

**Comment by akshgpt7** [comment]
Thanks! On it :)

**Comment by akshgpt7** [comment]
PEP-8 guidelines do not allow to use bare 'except'. I cannot figure out which errors to except in the following block of code:
```try:
            # Getting HTML page of repository
            html = requests.get(repository_link, timeout=8).text
        except:
            colors.error(
                "Enter the repositories url in given format "
                "[ https://github.com/username/repository_name ]")
            sys.exit(1)```
