### ISSUE TITLE
cannot fetch total stargazers list after 40 pages

### ISSUE THREAD

**Issue by shiyu22** [0xPrateek/Stardox#30]
The repo has 2.3k stargazers, but it can only show me 1,192 stargazers' info.

**Comment by 0xPrateek** [comment]
Can you share the Repository address and output data (if possible) ?

**Comment by shiyu22** [comment]
I fixed this problem, I found when I visit the website frequently, and 40th page prompts 'Contact Support', so it cannot find the 'Next' page(src/stardox.py line 134).

I add the code on line 130:
time.sleep(5)
and it fixed.

BTW, the Repository address: https://github.com/milvus-io/milvus
Welcome to star it.

**Comment by 0xPrateek** [comment]
I checked your commit https://github.com/shiyu22/Stardox/commit/1b7bea82334b10df29a7a9a00f05282bb1636595 .
Don't you think that adding a 5 sec sleep every time will make it slow.
If you are sure that contact page appears only after 40 ( or after multiples of 40) then adding a condition and doing time.sleep() after 40 is a good option rather sleeping for every next.
Else i add a condition to check weather next page is contact support and if it found support page it sleep for 5 sec.

What do you say ?

**Comment by shiyu22** [comment]
You're right, adding a 5 sec sleep will be slow.

It's a good idea for adding a condition to check weather next page is contact support and if it found support page it sleep for 5 sec.

**Comment by 0xPrateek** [comment]
Great..!! 
Thanks for coming up with the issue. I will push a commit very soon.
