### ISSUE TITLE
Search profile information using username

### ISSUE THREAD

**Issue by akshgpt7** [0xPrateek/Stardox#32]
As a new feature, using the username to fetch someone's github profile details can prove to be helpful. Also, their repositories will be listed and then one can look at the repo information.

**Comment by 0xPrateek** [comment]
Sounds Good..!
You can start working on it..!
Make sure to update your progress through commenting or referencing this issue

**Comment by akshgpt7** [comment]
@0xPrateek , Do I add a ```-u``` flag separately to specify username? 
It could be used as ```stardox.py -u [username]```  

Otherwise, we can also directly check if the entered argument is a username or a repository link.

I guess the ```-u``` flag is a better option?

**Comment by 0xPrateek** [comment]
Go with -u flag.

**Comment by 0xPrateek** [comment]
@akshgpt7 can you update the progress on this issue ?

**Comment by akshgpt7** [comment]
Yes I've almost completed it. Will push the code very soon!

**Comment by 0xPrateek** [comment]
great..!
