### ISSUE TITLE
adding more attempts for Entering correct infomation 

### ISSUE THREAD

**Issue by nitishsaini706** [0xPrateek/Stardox#34]
while user enters wrong info or wrong repository cli exit the script , instead of exiting cli we should give atleast 3 attempts ,or atleast one attempt before exiting which will create more ease of entering info to the user .

**Comment by jay24rajput** [comment]
Hey Can I work on this one??

**Comment by nitishsaini706** [comment]
im currently working on this

**Comment by jay24rajput** [comment]
Ohh, I am sorry mate. Confused you with the admin. :sweat_smile:

**Comment by 0xPrateek** [comment]
@nitishsaini706 Instead of doing this you can optimize the method which we are using to check if the url is of repository or not.

**Comment by nitishsaini706** [comment]
Or we can tell the user how to enter the input by providing an example

**Comment by 0xPrateek** [comment]
we are already giving an example when there is a wrong attempt

**Comment by nitishsaini706** [comment]
But why no giving it first to improve the user ease for entering input as
it will exit the terminal and user has to again run the script

**Comment by 0xPrateek** [comment]
we are already asking for "Repository address" as input (so url should be clear.) Instead of this we optimize the current method of detection of url's which are not repository url
