### ISSUE TITLE
Use a vitual environment for the application

### ISSUE THREAD

**Issue by rishabhKalakoti** [0xPrateek/Stardox#35]
Use something like `pipenv`?

It's not a good practice to install requirements globally for an application. We can use a virtual environment where the dependencies are installed only for the application, not globally.
This also reduces errors due to environment.

[problem with simple workflow](https://www.kennethreitz.org/essays/a-better-pip-workflow)

**Comment by rishabhKalakoti** [comment]
@0xPrateek let me know if you want this in your project, I can work on it.

**Comment by 0xPrateek** [comment]
I don't think we need this for stardox
