### ISSUE TITLE
Restructuring to add new arguments

### ISSUE THREAD

**Issue by akshgpt7** [0xPrateek/Stardox#36]
- The current code in ```if __name__ == '__main__':``` part can be made into a function, since if we add new features where this part is not required, it will not be called. (For example, in fetching details using username, this part will not be required.)

- Also, to add new arguments, I suggest making a separate arguments.py file, which will store the ```action``` classes of new arguments.

**Comment by 0xPrateek** [comment]
- I agree with the first point we can split that in function but this issue comes under  #25.
- For the second point, we don't need to create a separate file since we only have a limited number of arguments to handle.
