### ISSUE TITLE
Fixing Code color issues for windows users

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#4]
Adding windows colors support.

**Comment by ghost** [comment]
The whole colour structure should be modified by replacing ANSI with Colorama.

> ANSI escape character sequences have long been used to produce colored terminal text and cursor positioning on Unix and Macs. Colorama makes this work on Windows, too, by wrapping stdout, stripping ANSI sequences it finds (which would appear as gobbledygook in the output), and converting them into the appropriate win32 calls to modify the state of the terminal.
For details read here: https://pypi.org/project/colorama/

**Comment by 0xPrateek** [comment]
We are not supporting windows anymore
