### ISSUE TITLE
Replace Example images with example images with new logo

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Stardox#40]
- Logo of stardox is changed and the objective of this issue is to replace old logo example images present in readme.md with the new logo example images

**Comment by akshgpt7** [comment]
Can I fix this?

**Comment by 0xPrateek** [comment]
These are easy ones, not made for you. I'll assign you other pending issues and message me through  communication channel for more issues

**Comment by akshgpt7** [comment]
Sure!

**Comment by CaineArdayfio** [comment]
I can work on this, I'm a newbie:)

**Comment by 0xPrateek** [comment]
@CaineArdayfio  Okay I am assigning you this issue.

**Comment by 0xPrateek** [comment]
Fixed..
