### ISSUE TITLE
Problem to install and seek for help

### ISSUE THREAD

**Issue by Chandler-Song** [0xPrateek/Stardox#8]
![image](https://user-images.githubusercontent.com/23094571/54073508-da981780-42c2-11e9-977e-f31e48ee0fc1.png)
Could you help to check what is my problem and give me some suggestions？ Thanks a lot.

**Comment by 0xPrateek** [comment]
Hello @Chandler-Song,
We have committed some changes to our project ( You can check our latest commits [here](https://github.com/0xPrateek/Stardox/commits?author=0xPrateek)).
So, to solve this problem;
1- Clone the project again
     `git clone https://github.com/0xprateek/stardox`
2- For installing the required files.
     `cd stardox`
     `pip install -r requirements.txt`
We have also updated [Readme.md](https://github.com/0xPrateek/Stardox/blob/master/README.md) you can check it out too.
If this doesn't solve your problem feel free to reach us through issues :)

**Comment by Chandler-Song** [comment]
Sorted out. Thanks!

**Comment by 0xPrateek** [comment]
Sounds good. Happy Doxing..!
