### ISSUE TITLE
The process often breaks and cannot get full result of stargazers

### ISSUE THREAD

**Issue by Chandler-Song** [0xPrateek/Stardox#9]
![image](https://user-images.githubusercontent.com/23094571/54087531-b99cf880-438e-11e9-8408-f7484da5ae9e.png)

**Comment by Chandler-Song** [comment]
I try a couple of times and it cannot run constantly.

**Comment by 0xPrateek** [comment]
Hello @Chandler-Song ,
Thanks for creating the issue. It will help us to make this repository better.
Coming on to your Issue which you are facing, It seems you are using windows and as of now Stardox only supports Linux Environment.
I am looking forward for a pull request which can make stardox work on windows as well else we will push some commits soon which will make stardox compatible for windows.... :)

Happy Doxing..!
